services:
  protonmail-bridge:
    image: dancwilliams/protonmail-bridge:latest@sha256:25cc7a9007516f817d4d220d359e36558961de693935092361c8066184fd5d52
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  protonmail:
    name: protonmail
